language: node_js
node_js:
  - "8.0"
  - "7.0"
  - "6.0"
  - "5.0"
  - "4.0"

sudo: false

script:
  - "npm run test-coverage"
after_script:
  - "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
